name: inference-benchmark
functions:
- url: CreateStream.ipynb
  name: create-stream
  kind: job
- url: InferenceBenchmark.ipynb
  name: inference-benchmark
  kind: nuclio
workflows:
- name: main
  path: workflow.py
artifacts: []
artifact_path: ''
