name: dogs-vs-cats-pipeline
functions:
- url: DownloadS3.ipynb
  name: download-s3
  kind: job
  image: docker-registry.default-tenant.app.us-sales.iguazio-cd2.com:80/s3_image
workflows:
- name: main
  path: workflow.py
artifacts: []
artifact_path: ''
