name: dogs-vs-cats-demo
functions:
- url: DownloadS3.ipynb
  name: download-s3
  kind: job
  image: docker-registry.default-tenant.app.us-sales.iguazio-cd2.com:80/s3_image
- url: PrepData.ipynb
  name: prep-data
  kind: job
  image: mlrun/ml-models-gpu
- url: TrainModel.ipynb
  name: train-model
  kind: job
  image: mlrun/ml-models-gpu
workflows:
- name: main
  path: workflow.py
artifacts: []
artifact_path: ''
